### ISSUE TITLE
Pcre1 is at the end of its life cycle

### ISSUE THREAD

**Issue by zherczeg** [stealth/grab#8]
It is always great to see new grep projects. I always had the feeling that grepping is mostly limited by disk reading speed rather than regex engines, so it is worth to explore newer methods whenever it is possible.

Please be aware that the pcre1 development has has been ended since 2015, and projects (especially new ones) should use its new API called pcre2. Pcre1 is unlikely to see a new release, so some issues will never be fixed. Pcre2 is better, faster, etc. but most importantly: maintained.

**Comment by stealth** [comment]
Thx for the feedback. Yes, I know pcre1 is somewhat outdated, but its still
quite fast and working. It turned out that pcre2 API is somewhat different,
so the calls couldnt just be substituted. However, I added a new abstraction layer
so that pcre2 can be added in future. Thats also how hyperscan support was added
without touching the "base layer". When I started the project, there was no
pcre2. It also turned out that theres not so much speedup versus pcre1 with JIT (maybe 10%)
so the main bottleneck is indeed building of the file tree and distribution of files.
